<RootWidget>:
    TabbedPanel:
        do_default_tab: False
        
        TabbedPanelItem:
            text: 'Item 1'
            BoxLayout:
        
        TabbedPanelItem:
            on_touch_move:    stu
            bold: True
            text: 'Item 2'
            BoxLayout:
        
        TabbedPanelItem:
            text: 'Item 3'
            BoxLayout:
        
        TabbedPanelItem:
        	text:'Item 3'
        	Boxlayout:


