<RootWidget>:
    do_default_tab: False
        
    TabbedPanelItem:
        text: 'Monday'
      	BoxLayout:
      		orientation: 'horizontal'
      		BoxLayout:
      			orientation: 'vertical'
      			Button:
      				text: 'Edit'
      				on_press: root.edit(label11,
      			Button:
      				
        
    TabbedPanelItem:
        text: 'Tuesday'
        BoxLayout:
        
    TabbedPanelItem:
        text: 'Wednesday'
        BoxLayout:


